#!/bin/bash
if [ "$1" = "update" ]
then
  curl -S -s -o /usr/local/bin/coolioupdate.sh https://raw.githubusercontent.com/elnepik/Coolio/master/coolioupdate.sh
  chmod +x /usr/local/bin/coolioupdate.sh
  bash /usr/local/bin/coolioupdate.sh
elif [ "$1" = "status" ]
then
echo "Getting latest version"
  curl -S -s -o /usr/local/bin/latestversion https://raw.githubusercontent.com/elnepik/Coolio/master/version
  cat /usr/local/bin/latestversion | read lcoolv
  echo "$lcoolv"
  rm /usr/local/bin/latestversion
fi
