#!/bin/bash
echo "Bruh the updates don't do anything stop it."
if [ "$1" = "update" ]
then
  curl -o /usr/local/bin/coolioupdate.sh https://raw.githubusercontent.com/elnepik/Coolio/master/coolioupdate.sh
  chmod +x /usr/local/bin/coolioupdate.sh
  bash /usr/local/bin/coolioupdate.sh
fi
