#!/bin/bash
echo "Hello update test 1 success!"
if [ "$1" = "update" ]
then
  curl -o /usr/local/bin/coolioupdate.sh https://raw.githubusercontent.com/elnepik/Coolio/master/coolioupdate.sh
  chmod +x /usr/local/bin/coolioupdate.sh
  bash /usr/local/bin/coolioupdate.sh
fi
